## Phase 1A - Dataset Understanding + RUL Engineering

In [1]:
import pandas as pd
import numpy as np

# Define column names
columns = (
    ['engine_id', 'cycle']
    + [f'op_setting_{i}' for i in range(1, 4)]
    + [f'sensor_{i}' for i in range(1, 22)]
)

# Load training data
train_df = pd.read_csv(
    '../data/raw/train/train_FD001.txt',
    sep=r'\s+',
    header=None
)

# Remove extra empty columns if present
train_df.dropna(axis=1, inplace=True)

# Assign column names
train_df.columns = columns

# Preview data
train_df.head()

,engine_id,cycle,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [2]:
print("Shape:", train_df.shape)

Shape: (20631, 26)

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20631 entries, 0 to 20630
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   engine_id     20631 non-null  int64
 1   cycle         20631 non-null  int64
 2   op_setting_1  20631 non-null  float64
 3   op_setting_2  20631 non-null  float64
 4   op_setting_3  20631 non-null  float64
 5   sensor_1      20631 non-null  float64
 6   sensor_2      20631 non-null  float64
 7   sensor_3      20631 non-null  float64
 8   sensor_4      20631 non-null  float64
 9   sensor_5      20631 non-null  float64
 10  sensor_6      20631 non-null  float64
 11  sensor_7      20631 non-null  float64
 12  sensor_8      20631 non-null  float64
 13  sensor_9      20631 non-null  float64
 14  sensor_10     20631 non-null  float64
 15  sensor_11     20631 non-null  float64
 16  sensor_12     20631 non-null  float64
 17  sensor_13     20631 non-null  float64
 18  sensor_14     20631 non-null  float64
 19  sensor_15     20631 non-null  float64
 20  sensor_16     20631 non-null  float64
 21  sensor_17     20631 non-null  int64
 22  sensor_18     20631 non-null  int64
 23  sensor_19     20631 non-null  float64
 24  sensor_20     20631 non-null  float64
 25  sensor_21     20631 non-null  float64
dtypes: float64(22), int64(4)
memory usage: 4.1 MB

In [4]:
# Find maximum cycle for each engine
max_cycles = train_df.groupby('engine_id')['cycle'].max().reset_index()

max_cycles.columns = ['engine_id', 'max_cycle']

# Merge back
train_df = train_df.merge(max_cycles, on='engine_id')

# Compute Remaining Useful Life
train_df['RUL'] = train_df['max_cycle'] - train_df['cycle']

# Preview
train_df[['engine_id', 'cycle', 'max_cycle', 'RUL']].head()

   engine_id  cycle  max_cycle  RUL
0          1      1        192  191
1          1      2        192  190
2          1      3        192  189
3          1      4        192  188
4          1      5        192  187

In [5]:
train_df[['engine_id', 'cycle', 'max_cycle', 'RUL']].tail()

       engine_id  cycle  max_cycle  RUL
20626        100    196        200    4
20627        100    197        200    3
20628        100    198        200    2
20629        100    199        200    1
20630        100    200        200    0

In [6]:
train_df.to_csv(
    '../data/processed/train_with_rul.csv',
    index=False
)

## Phase 1B — Sensor Analysis + Feature Engineering

In [7]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')

In [8]:
sensor_cols = [col for col in train_df.columns if 'sensor' in col]

print(sensor_cols)

['sensor_1', 'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5', 'sensor_6', 'sensor_7', 'sensor_8', 'sensor_9', 'sensor_10', 'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15', 'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20', 'sensor_21']

In [9]:
#Variance Analysis - Purpose: Find sensors that barely change.

#Low-variance sensors contribute almost nothing.
variance = train_df[sensor_cols].var().sort_values()

print(variance)

sensor_1     0.000000e+00
sensor_10    0.000000e+00
sensor_19    0.000000e+00
sensor_18    0.000000e+00
sensor_16    1.926023e-34
sensor_5     3.155597e-30
sensor_6     1.929279e-06
sensor_15    1.406628e-03
sensor_8     5.038938e-03
sensor_13    5.172330e-03
sensor_21    1.171825e-02
sensor_20    3.266927e-02
sensor_11    7.133568e-02
sensor_2     2.500533e-01
sensor_12    5.439850e-01
sensor_7     7.833883e-01
sensor_17    2.398667e+00
sensor_3     3.759099e+01
sensor_4     8.101089e+01
sensor_14    3.639005e+02
sensor_9     4.876536e+02
dtype: float64

In [10]:
#These contribute almost no predictive information.
drop_sensors = [
    'sensor_1',
    'sensor_5',
    'sensor_10',
    'sensor_16',
    'sensor_18',
    'sensor_19'
]

In [11]:
# Drop low-variance sensors
train_df = train_df.drop(columns=drop_sensors)

# Verify remaining columns
print(train_df.columns)

Index(['engine_id', 'cycle', 'op_setting_1', 'op_setting_2', 'op_setting_3',
       'sensor_2', 'sensor_3', 'sensor_4', 'sensor_6', 'sensor_7', 'sensor_8',
       'sensor_9', 'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14',
       'sensor_15', 'sensor_17', 'sensor_20', 'sensor_21', 'max_cycle', 'RUL'],
      dtype='object')

In [12]:
train_df = train_df.drop(columns=['op_setting_3'])

In [13]:
#Define Final Feature Set
selected_features = [
    'sensor_2',
    'sensor_3',
    'sensor_4',
    'sensor_6',
    'sensor_7',
    'sensor_8',
    'sensor_9',
    'sensor_11',
    'sensor_12',
    'sensor_13',
    'sensor_14',
    'sensor_15',
    'sensor_17',
    'sensor_20',
    'sensor_21'
]

In [14]:
# Normalize Features
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

train_df[selected_features] = scaler.fit_transform(
    train_df[selected_features]
)

In [15]:
# Verify Scaling
train_df[selected_features].describe()

,sensor_2,sensor_3,sensor_4,sensor_6,sensor_7,sensor_8,sensor_9,sensor_11,sensor_12,sensor_13,sensor_14,sensor_15,sensor_17,sensor_20,sensor_21
count,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000
mean,0.443052,0.424746,0.450435,0.980321,0.566459,0.297957,0.195248,0.411410,0.580697,0.317871,0.226095,0.451118,0.434221,0.524241,0.546127
std,0.150618,0.133664,0.151935,0.138898,0.142527,0.107554,0.099089,0.158981,0.157261,0.105763,0.098442,0.144306,0.129064,0.140114,0.149476
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.335843,0.331807,0.339467,1.000000,0.476651,0.227273,0.140761,0.297619,0.484009,0.235294,0.171870,0.346287,0.333333,0.434109,0.452361
50%,0.430723,0.415522,0.435348,1.000000,0.578100,0.287879,0.174684,0.392857,0.594883,0.308824,0.209516,0.438630,0.416667,0.534884,0.557443
75%,0.539157,0.508829,0.545324,1.000000,0.669887,0.363636,0.213991,0.505952,0.695096,0.382353,0.249613,0.541362,0.500000,0.627907,0.652582
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [16]:
#Save Processed Dataset
train_df.to_csv(
    '../data/processed/train_final_processed.csv',
    index=False
)